-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.admin_users
(
    id integer NOT NULL,
    first_name character varying(25) NOT NULL,
    last_name character varying(25) NOT NULL,
    user_type_id integer NOT NULL,
    user_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.cities
(
    id integer NOT NULL,
    name character varying(30) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.employees
(
    id integer NOT NULL,
    first_name character varying(30) NOT NULL,
    last_name character varying(30) NOT NULL,
    identity_number character varying(11) NOT NULL,
    date_of_birth date NOT NULL,
    user_type_id integer NOT NULL,
    user_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.employers
(
    id integer NOT NULL,
    company_name character varying(50) NOT NULL,
    web_address character varying(50) NOT NULL,
    phone_number character varying(12) NOT NULL,
    user_type_id integer NOT NULL,
    user_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.job_titles
(
    id integer NOT NULL,
    title character varying(50) NOT NULL,
    city_id integer,
    min_salary integer,
    max_salary integer,
    open_position_count integer,
    created_date date,
    application_deadline date,
    is_active boolean,
    employer_id integer,
    PRIMARY KEY (id)
);

CREATE TABLE public.user_activations
(
    id integer NOT NULL,
    activation_code character varying(50) NOT NULL,
    is_confirmed boolean NOT NULL,
    confirmation_date date NOT NULL,
    user_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.user_activations_by_admin_users
(
    id integer NOT NULL,
    confirmed_employee_id integer NOT NULL,
    confirmation_date date NOT NULL,
    is_confirmed boolean NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.user_types
(
    id integer NOT NULL,
    user_type character varying(30) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.users
(
    id integer NOT NULL,
    email character varying(50) NOT NULL,
    password character varying(500),
    password_again character varying(500) NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE public.admin_users
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.admin_users
    ADD FOREIGN KEY (user_type_id)
    REFERENCES public.user_types (id)
    NOT VALID;


ALTER TABLE public.admin_users
    ADD FOREIGN KEY (id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.employers
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.employers
    ADD FOREIGN KEY (id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.user_activations
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.employees
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.user_activations_by_admin_users
    ADD FOREIGN KEY (confirmed_employee_id)
    REFERENCES public.employees (id)
    NOT VALID;


ALTER TABLE public.employees
    ADD FOREIGN KEY (user_type_id)
    REFERENCES public.user_types (id)
    NOT VALID;


ALTER TABLE public.job_titles
    ADD FOREIGN KEY (city_id)
    REFERENCES public.cities (id)
    NOT VALID;


ALTER TABLE public.job_titles
    ADD FOREIGN KEY (employer_id)
    REFERENCES public.employers (id)
    NOT VALID;


ALTER TABLE public.employers
    ADD FOREIGN KEY (user_type_id)
    REFERENCES public.user_types (id)
    NOT VALID;

END;